version: '2.4'
services:
  front:
    container_name: ducksmanager-web
    build:
      context: .
      target: web
    depends_on:
      - php-flex
    restart: always
    networks:
      - workspace_global-front-network
      - dm-network

  php-flex:
    container_name: ducksmanager-php
    build:
      context: .
      target: app
    restart: always
    volumes:
      - dm_sessions:/tmp/sessions
    networks:
      - dm-network
      - dm-server_front-network

networks:
  dm-network:
  workspace_global-front-network:
    external: true
  dm-server_front-network:
    external: true
