version: '2.4'
services:
  front:
    container_name: ducksmanager-web
    image: ghcr.io/bperel/ducksmanager-web
    depends_on:
      - php-flex
    restart: always
    networks:
      - public-network
      - dm-network

  php-flex:
    container_name: ducksmanager-php
    image: ghcr.io/bperel/ducksmanager-php
    restart: always
    volumes:
      - dm_sessions:/tmp/sessions
    networks:
      - dm-network
      - dm-server_front-network

  sentry-relay:
    image: getsentry/relay
    restart: always
    container_name: sentry
    volumes:
      - ./config/sentry-relay:/work/.relay
    networks:
      - public-network


networks:
  dm-network:
  public-network:
    external: true
  dm-server_front-network:
    external: true

volumes:
  dm_sessions:
    external: true
